### ISSUE TITLE
Empty result on every queries

### ISSUE THREAD

**Issue by mortymacs** [Marskey/telescope-sg#2]
Hi,

I've installed and tested the extension, but nothing it returns as a result:
![image](https://github.com/Marskey/telescope-sg/assets/1261448/1abd8575-93bb-4e4d-b719-89338892fa1a)

but when I run the command in terminal, it produces results:
```shell
$ ast-grep --json -p '$A()'
...
  "file": "./static/tabbed-0.7/tabbed.c",
  "language": "C",
  "metaVariables": {
    "single": {
      "A": {
        "text": "cleanup",
        "range": {
          "byteOffset": {
            "start": 29639,
            "end": 29646
          },
          "start": {
            "line": 1371,
            "column": 1
          },
          "end": {
            "line": 1371,
            "column": 8
          }
        }
      }
    },
    "multi": {},
    "transformed": {}
  }
}
]
```

Config:
ast_grep: 0.9.1
NVIM v0.9.1

```lua
  ast_grep = {
      command = {
          "ast-grep",
          "--json",
          "-p",
      },
      grep_open_files = false,
      lang = nil,
  },
  ...
require("telescope").load_extension("ast_grep")
```

**Comment by Marskey** [comment]
ast_grep need >= 0.10.0

**Comment by SushritPasupuleti** [comment]
I have `ast-grep` installed, but have the same issue. I have the command modified to `ast-grep` instead of `sg` like above as well since I'm on linux.

Is the binary's location hardcoded by any chance?

**Comment by mortymacs** [comment]
> I have `ast-grep` installed, but have the same issue. I have the command modified to `ast-grep` instead of `sg` like above as well since I'm on linux.
> 
> Is the binary's location hardcoded by any chance?

In the config, if you don't mention the `command` attribute, then it will load the default config which has the `sg` command: https://github.com/Marskey/telescope-sg/blob/main/lua/telescope/_extensions/ast_grep.lua#L148-L152

**Comment by Marskey** [comment]
> I have `ast-grep` installed, but have the same issue. I have the command modified to `ast-grep` instead of `sg` like above as well since I'm on linux.
> 
> Is the binary's location hardcoded by any chance?

can you offer the ast-grep version?
and if you can get results from terminal with the same pattern

**Comment by SushritPasupuleti** [comment]
> > I have `ast-grep` installed, but have the same issue. I have the command modified to `ast-grep` instead of `sg` like above as well since I'm on linux.
> > Is the binary's location hardcoded by any chance?
> 
> can you offer the ast-grep version? and if you can get results from terminal with the same pattern

I ended up building from source earlier, and it seemed to fix my problem. For some reason, the direct cargo install version wasn't working.

**Comment by mortymacs** [comment]
I just upgraded the ast-grep to the version `0.10.0`, But the headth-check shows error:
![image](https://github.com/Marskey/telescope-sg/assets/1261448/79f45dd8-3e0a-49f2-afe5-b85c67b59729)

Still doesn't work.

**Comment by Marskey** [comment]
HI @mortymacs 
```lua
  ast_grep = {
      command = {
          "ast-grep",
          "--json=stream",
          "-p",
      },
      grep_open_files = false,
      lang = nil,
  },
  ...
require("telescope").load_extension("ast_grep")
```
plz, change the `--json` to `--json=stream`, its added in 0.10.0, I'll try add this check to code.

**Comment by mortymacs** [comment]
> HI @mortymacs
> 
> ```lua
>   ast_grep = {
>       command = {
>           "ast-grep",
>           "--json=stream",
>           "-p",
>       },
>       grep_open_files = false,
>       lang = nil,
>   },
>   ...
> require("telescope").load_extension("ast_grep")
> ```
> 
> plz, change the `--json` to `--json=stream`, its added in 0.10.0, I'll try add this check to code.

Hi @Marskey ,

I already did that, the command works fine:
![image](https://github.com/Marskey/telescope-sg/assets/1261448/a81c4c82-22be-4221-a2d9-8803918f5707)
But in nvim it shows nothing:
![image](https://github.com/Marskey/telescope-sg/assets/1261448/deba1a08-6aef-4532-8e13-ecc70589e730)

This is my current config: https://github.com/mortymacs/dotfiles/blob/main/home-manager/common/nvim/lua/lua/finder.lua#L53-L61

**Comment by TxHawks** [comment]
I'm hitting the same issue on a mac. `:checkhealth` is fine, `sg` is `0.10.0` and searching on the command line works but telescope yields no results.

A small nuance is that greping for `require` returns results, but `require($A)` doesn't.

**Comment by Marskey** [comment]
add     `generic_sorter = require("telescope.sorters").get_generic_fuzzy_sorter` to telescope's config
like 
```lua
  defaults = {
    vimgrep_arguments = {
      "rg",
      "-L",
      "--color=never",
      "--no-heading",
      "--with-filename",
      "--line-number",
      "--column",
      "--smart-case",
    },
    generic_sorter = require("telescope.sorters").get_generic_fuzzy_sorter,
  },
```
should help.

**Comment by Marskey** [comment]
and also #4 solved this issue

**Comment by mortymacs** [comment]
Thank you!

**Comment by fabiobaser** [comment]
For me, the error persists. Even with the new version and the generic sorter.

I have the following in my nvim-messages:
`[telescope] [WARN  10:15:19] /Users/.../.local/share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:489: Finder failed with msg:  ...share/nvim/lazy/tele
scope.nvim/lua/telescope/sorters.lua:430: bad argument #1 to 'pow' (number expected, got nil)
`

**Comment by Marskey** [comment]
> For me, the error persists. Even with the new version and the generic sorter.
> 
> I have the following in my nvim-messages: `[telescope] [WARN 10:15:19] /Users/.../.local/share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:489: Finder failed with msg: ...share/nvim/lazy/tele scope.nvim/lua/telescope/sorters.lua:430: bad argument #1 to 'pow' (number expected, got nil) `

Hi @fabiobaser can you checkout to last version that not contain #4, and try again?

**Comment by Marskey** [comment]
> add `generic_sorter = require("telescope.sorters").get_generic_fuzzy_sorter` to telescope's config like
> 
> ```lua
>   defaults = {
>     vimgrep_arguments = {
>       "rg",
>       "-L",
>       "--color=never",
>       "--no-heading",
>       "--with-filename",
>       "--line-number",
>       "--column",
>       "--smart-case",
>     },
>     generic_sorter = require("telescope.sorters").get_generic_fuzzy_sorter,
>   },
> ```
> 
> should help.

This is not necessary since I change sorter to highlight_only.
@fabiobaser

**Comment by fabiobaser** [comment]
I tried "last version without #4" with commit hash "b599ae559d80cec643cf6d9478c745ea218c4642" and that does work perfectly!

Edit: `const $A` shows results but `console.log($$$)` shows "0/55" Results but the newest version seems to fix it completely.
