### ISSUE TITLE
HOw to setup?

### ISSUE THREAD

**Issue by pedro757** [Marskey/telescope-sg#5]
I get `[telescope.run_command]: Unknown command` with the following config in `after/telescope.lua`:
```lua 
require("telescope").setup {
  extensions = {
    ast_grep = {
      command = {
        "ast-grep",
        "--json=stream",
      },
      grep_open_files = false,
      lang = nil,
    },
  }
}
```

**Comment by Marskey** [comment]
you need `require('telescope').load_extension('ast_grep')` too

**Comment by rootex-** [comment]
> you need `require('telescope').load_extension('ast_grep')` too

@Marskey better put this somewhere into documentation as a reminder
