### ISSUE TITLE
install dependency with packer

### ISSUE THREAD

**Issue by hesxenon** [Marskey/telescope-sg#6]
the only thing preventing me from installing this plugin is that it requires an imperatively installed global dependency (`npm i -g @ast-grep/cli`).

This is easy to forget when setting up a new machine (because I might have f'd up my configs again :sweat_smile:).

Is there a way to get packer or sth else to install the dependency for me, in a declarative way?

**Comment by Marskey** [comment]
if you use packer.nvim
```lua
use {'marskey/telescope-sg', run = 'npm i -g @ast-grep/cli'}
 ``` 
this should help
