### ISSUE TITLE
Not working with error: attempt to get length of local 'icon' (a nil value)

### ISSUE THREAD

**Issue by rootex-** [Marskey/telescope-sg#8]
I get this error in :messages :
```
[telescope] [WARN  11:04:31] /Users/.../.local/share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:489: Fin
der failed with msg:  ...lazy/telescope-sg/lua/telescope/_extensions/ast_grep.lua:99: attempt to get length of local
'icon' (a nil value)
```

The Telescope picker window is empty:

<img width="888" alt="Screenshot 2023-10-05 at 11 10 40" src="https://github.com/Marskey/telescope-sg/assets/8237030/a2a4efb1-b677-4bf4-81ba-6512237a15ee">

**Comment by Marskey** [comment]
did u install `nvim-tree/nvim-web-devicons`?
and what the version of telescope you installed

**Comment by rootex-** [comment]
> did u install `nvim-tree/nvim-web-devicons`? and what the version of telescope you installed

It was 0.1.1 hardcoded in my config! I updated Telescope to 0.1.3 and now everything is working, thank you!

**Comment by rootex-** [comment]
One more question: 
"if" works fine:
<img width="1087" alt="Screenshot 2023-10-05 at 18 51 52" src="https://github.com/Marskey/telescope-sg/assets/8237030/5395d712-c78a-434f-9bca-cfa9421a0c48">

"if not" fails to output anything:
<img width="1119" alt="Screenshot 2023-10-05 at 18 52 39" src="https://github.com/Marskey/telescope-sg/assets/8237030/3e2690d4-9923-419b-8b8d-58e3d43b8dde">

**Comment by Marskey** [comment]
It is sg that return nothing, not telescope-sg' issue

**Comment by Marskey** [comment]
CLOSED since there is no other questions
